backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "images"

collections:
  - name: "illustrations" # Used in routes, e.g., /admin/collections/blog
    label: "Illustrations post" # Used in the UI
    folder: "_posts/illustrations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "illustrations"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", media_library: { config: { multiple: true } } }
      - {label: "Image size", name: "image_size", widget: "string"}
      - {label: "Gallery", name: "galleryImages", widget: "list", field: {label: Image, name: image, widget: image, media_library: { config: { multiple: true } } } }
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", optional: true}

  - name: "crochet" # Used in routes, e.g., /admin/collections/blog
    label: "Crochet post" # Used in the UI
    folder: "_posts/crochet" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "crochet"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", media_library: { config: { multiple: true } } }
      - {label: "Gallery", name: "galleryImages", widget: "list", field: {label: Image, name: image, widget: image, media_library: { config: { multiple: true } } } }
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", optional: true}